# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  wavetoy3-benchmarks:
    dependencies:
      - base
      - wavetoy3
      - criterion
    ghc-options:
      - -ddump-to-file -ddump-simpl
      - -O2
      - -funbox-strict-fields
      - -fexcess-precision
      - -fllvm -pgmlo /opt/local/bin/opt-mp-3.9 -pgmlc /opt/local/bin/llc-mp-3.9
      - -optlo-O3
      - -optlo-enable-fp-mad
      - -optlo-enable-no-infs-fp-math
      - -optlo-enable-no-nans-fp-math
      - -optlo-enable-unsafe-fp-math
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: wavetoy3 is a Haskell WaveToy implementation.
executables:
  wavetoy3:
    dependencies:
      - base
      - wavetoy3
    ghc-options:
      - -ddump-to-file -ddump-simpl -ddump-stranal
      - -O2
      - -funbox-strict-fields
      - -fexcess-precision
      - -fllvm -pgmlo /opt/local/bin/opt-mp-3.9 -pgmlc /opt/local/bin/llc-mp-3.9
      - -optlo-O3
      - -optlo-enable-fp-mad
      - -optlo-enable-no-infs-fp-math
      - -optlo-enable-no-nans-fp-math
      - -optlo-enable-unsafe-fp-math
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
  - CHANGELOG.rst
  - LICENSE.rst
  - package.yaml
  - README.rst
  - stack.yaml
ghc-options: -Wall
github: eschnett/wavetoy3
library:
  dependencies:
    - QuickCheck
    # - ad
    - base
    - comonad
    - constraints
    - distributive
    - extra
    - hmatrix
    - ieee754
    # - ifcxt
    - ilist
    # - linear
    - mtl
    # - quadrature
    - unfoldable
    - validity
    - validity-vector
    - vector
    - vector-integration
    - vector-space
  ghc-options:
    - -ddump-to-file -ddump-simpl -ddump-stranal
    - -O2
    - -funbox-strict-fields
    - -fexcess-precision
    - -fllvm -pgmlo /opt/local/bin/opt-mp-3.9 -pgmlc /opt/local/bin/llc-mp-3.9
    - -optlo-O3
    - -optlo-enable-fp-mad
    - -optlo-enable-no-infs-fp-math
    - -optlo-enable-no-nans-fp-math
    - -optlo-enable-unsafe-fp-math
  source-dirs: library
license: MIT
maintainer: Erik Schnetter
name: wavetoy3
synopsis: wavetoy3 is a Haskell WaveToy implementation
tests:
  wavetoy3-test-suite:
    dependencies:
      - QuickCheck
      - base
      - comonad
      - either
      - extra
      - ieee754
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-quickcheck
      - unfoldable
      - validity
      - vector
      - vector-space
      - wavetoy3
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '1.0.0'
